// Ülke / şehir / dil seçenek verileri (form dropdown'ları için)

export const COUNTRIES = [
  "Germany", "United Kingdom", "France", "Netherlands", "Belgium", "Austria",
  "Switzerland", "Italy", "Spain", "Portugal", "Sweden", "Norway", "Denmark",
  "Finland", "Ireland", "Poland", "Romania", "Greece", "Bulgaria", "Russia",
  "Ukraine", "United States", "Canada", "United Arab Emirates", "Saudi Arabia",
  "Qatar", "Kuwait", "Bahrain", "Oman", "Iraq", "Israel", "Azerbaijan",
  "Kazakhstan", "Turkey", "Egypt", "Morocco", "Algeria", "Tunisia", "Libya",
  "Australia", "Other",
];

// En sık kaynak ülkeler için büyük şehirler; listede olmayan ülkede serbest metin
export const CITIES: Record<string, string[]> = {
  Germany: ["Berlin", "München", "Hamburg", "Köln", "Frankfurt", "Stuttgart", "Düsseldorf"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Liverpool"],
  France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Strasbourg"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Liège"],
  Austria: ["Vienna", "Graz", "Linz", "Salzburg"],
  Switzerland: ["Zürich", "Geneva", "Basel", "Bern"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Florence"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Málaga"],
  Portugal: ["Lisbon", "Porto", "Braga"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö"],
  Norway: ["Oslo", "Bergen", "Trondheim"],
  Denmark: ["Copenhagen", "Aarhus", "Odense"],
  Finland: ["Helsinki", "Espoo", "Tampere"],
  Ireland: ["Dublin", "Cork", "Galway"],
  Poland: ["Warsaw", "Kraków", "Wrocław", "Gdańsk"],
  Romania: ["Bucharest", "Cluj-Napoca", "Timișoara"],
  Greece: ["Athens", "Thessaloniki", "Patras"],
  Bulgaria: ["Sofia", "Plovdiv", "Varna"],
  Ukraine: ["Kyiv", "Kharkiv", "Odesa", "Lviv"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Miami"],
  Canada: ["Toronto", "Montreal", "Vancouver", "Calgary"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Dammam"],
  Qatar: ["Doha", "Al Rayyan"],
  Kuwait: ["Kuwait City", "Hawalli"],
  Bahrain: ["Manama", "Riffa"],
  Oman: ["Muscat", "Salalah"],
  Iraq: ["Baghdad", "Erbil", "Basra", "Mosul", "Sulaymaniyah"],
  Israel: ["Tel Aviv", "Jerusalem", "Haifa"],
  Azerbaijan: ["Baku", "Ganja"],
  Kazakhstan: ["Almaty", "Astana", "Shymkent"],
  Turkey: ["İstanbul", "Ankara", "İzmir", "Antalya", "Bursa"],
  Egypt: ["Cairo", "Alexandria", "Giza"],
  Morocco: ["Casablanca", "Rabat", "Marrakesh"],
  Algeria: ["Algiers", "Oran", "Constantine"],
  Tunisia: ["Tunis", "Sfax", "Sousse"],
  Libya: ["Tripoli", "Benghazi", "Misrata"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
  Russia: ["Moscow", "Saint Petersburg", "Kazan"],
};

// Tercih edilen dil (endonim etiketlerle)
export const LANGUAGES = [
  { code: "tr", label: "Türkçe" },
  { code: "en", label: "English" },
  { code: "de", label: "Deutsch" },
  { code: "fr", label: "Français" },
  { code: "ar", label: "العربية" },
  { code: "ru", label: "Русский" },
  { code: "es", label: "Español" },
  { code: "it", label: "Italiano" },
  { code: "nl", label: "Nederlands" },
  { code: "other", label: "Other" },
];
